### ISSUE TITLE
Arrows after social logos

### ISSUE THREAD

**Issue by ghost** [Otavie/altschool-2023-photocard#13]
The arrows after the social button that is pointing at studen't link dosen't seem neccessary. In my opinion it looks a little bit weired and would be a lot nicer if removed.
![image](https://i.imgur.com/sQWNCNu.png)

**Comment by Otavie** [comment]
Can you show a GUI of how it will look like when it is removed

**Comment by ghost** [comment]
Created a new branch and made a pull request check it out. Also included a commit message

**Comment by Otavie** [comment]
Issue resolved. Thanks

**Comment by Otavie** [comment]
Issue resolved and closed. Thanks
