### ISSUE TITLE
a elements do not have [target] attributes

### ISSUE THREAD

**Issue by Aopeyemi98** [Otavie/altschool-2023-photocard#23]
I tried to analyze your work and I realized that the links to the social media does not have a `target` opening. I'd like to fix this issue.

**Comment by Otavie** [comment]
The target that will be added, what will it do? Is it to enable the link to open in another tab or what? Just explain what the code/feature u will be adding will do. Thanks

ALSO FEEL FREE TO STAR THE REPO FOR THE OPEN SOURCE PROJECT. THANKS

**Comment by Otavie** [comment]
You have done that already. Thanks. Meanwhile, two things remain:
- Add ur name to Contributors.md
- Star the Open Source Repo

Thanks

**Comment by Aopeyemi98** [comment]
I have added my name to the contributors link and also starred the file. Thanks for this privilege once again I'm so **excited**
