### ISSUE TITLE
[Improvement] The Standard structure of unordered list element is not achieved

### ISSUE THREAD

**Issue by AbdulrahmanIsmael** [Otavie/altschool-2023-photocard#44]
## The issue
In the `index.html` file, each '.photocard' element contains an unordered list element `<ul>` with a directly nested list item element `<li>`. If you want to include anchor elements `<a>` for each list item, they should be placed inside the `<li>` element rather than the opposite. This practice can be beneficial for __SEO__ and following best practices.

If you need me to handle this issue, please let me know.

Thanks.

**Comment by Otavie** [comment]
Go ahead and make the adjustment and raise a PR
